name: Node CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, windows-latest]
        node: [18]
        include:
        - os: windows-latest
          commandPrefix: ''
        - os: ubuntu-20.04
          commandPrefix: xvfb-run
        - os: ubuntu-latest
          commandPrefix: xvfb-run
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: yarn
    - name: yarn install
      run: yarn install
    - name: yarn test
      run: ${{ matrix.commandPrefix }} yarn run test:ci
      env:
        CI: true
    - name: Upload coverage to Codecov
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 18}}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/clover.xml
